version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: maroonfive 
      MYSQL_DATABASE: atividade
      MYSQL_USER: root
      MYSQL_PASSWORD: maroonfive
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
